# Generated by Django 5.1.15 on 2026-09-27 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='평가 항목명')),
                ('description', models.TextField(blank=True, verbose_name='항목 설명')),
                ('weight', models.PositiveIntegerField(verbose_name='가중치(%)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '평가 기준 항목',
                'verbose_name_plural': '평가 기준 항목 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', '임시 저장'), ('SUBMITTED', '제출 완료')], default='DRAFT', max_length=20, verbose_name='평가 상태')),
                ('raw_score', models.FloatField(default=0.0, verbose_name='개인 평가 점수')),
                ('final_score', models.FloatField(default=0.0, verbose_name='최종 산출 점수')),
                ('is_capped', models.BooleanField(default=False, verbose_name='100점 상한 적용 여부')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='최종 제출일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='피평가자(직원)')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='평가자(매니저)')),
            ],
            options={
                'verbose_name': '인사 평가서',
                'verbose_name_plural': '인사 평가서 목록',
                'unique_together': {('employee', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='부여 점수(1~5점)')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_scores', to='evaluations.evaluationcriteria', verbose_name='평가 항목')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationreview', verbose_name='평가서')),
            ],
            options={
                'verbose_name': '항목별 평가 점수',
                'verbose_name_plural': '항목별 평가 점수 목록',
                'unique_together': {('review', 'criteria')},
            },
        ),
    ]
