# Generated by Django 5.2.17 on 2026-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_evaluationcriteria_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='매니저 총평'),
        ),
        migrations.AddField(
            model_name='evaluationreview',
            name='improvements',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='개선 제언'),
        ),
        migrations.AddField(
            model_name='evaluationreview',
            name='strengths',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='주요 강점'),
        ),
    ]
