# Generated by Django 5.1.15 on 2026-09-27 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='팀명')),
                ('bonus_score', models.FloatField(default=0.0, verbose_name='팀 보너스 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='담당 매니저')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀 목록',
                'ordering': ['name'],
            },
        ),
    ]
